spring:
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: 135790
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    user: postgres
    password: 135790
    liquibase-schema: core
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port : 8082
security:
  jwt:
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlq0+htPhjCxEcbLzKjDq
      VWCSDuFIPl5PYWFM0gmLg74jxCLXsItsZvvgpQKc+APorna3WtMO9RoN5+7W9K3+
      qJpxlzP0vOzx7xoNTx+OSmfUwJjuA1zdfA/Y5+OXLtvyNzz2V8WOmxLhek6LtwjR
      eOCuCuHBSs8ex0LDFuUmkIlyfc1hebeei3EUIKODs8sZoeTFVJxiX6+pyjanBlL1
      Rb6gXQUQ3iPzP1ymhW7aCbYzrJsOnnwEx5T9shSgq8FYsetk46UCu8Iv6RtZld2R
      hq082Yik5+2wowXT6vpNQJ3Yj8MQPiT7s+XYd4gmBFPwiVapLEnuzYReTkQuF8RZ
      0QIDAQAB
      -----END PUBLIC KEY-----
